#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x58D0EE648A48B3BB (faure@kde.org)
#
Name     : kded
Version  : 5.49.0
Release  : 2
URL      : https://download.kde.org/stable/frameworks/5.49/kded-5.49.0.tar.xz
Source0  : https://download.kde.org/stable/frameworks/5.49/kded-5.49.0.tar.xz
Source99 : https://download.kde.org/stable/frameworks/5.49/kded-5.49.0.tar.xz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : LGPL-2.0 LGPL-2.1
Requires: kded-bin
Requires: kded-data
Requires: kded-license
Requires: kded-man
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : kcrash-dev
BuildRequires : kdbusaddons-dev
BuildRequires : kinit-dev
BuildRequires : qtbase-dev qtbase-extras mesa-dev

%description
# KDED
Central daemon of KDE work spaces
## Introduction
KDED stands for KDE Daemon which isn't very descriptive.
KDED runs in the background and performs a number of small tasks.
Some of these tasks are built in, others are started on demand.

%package bin
Summary: bin components for the kded package.
Group: Binaries
Requires: kded-data
Requires: kded-license
Requires: kded-man

%description bin
bin components for the kded package.


%package data
Summary: data components for the kded package.
Group: Data

%description data
data components for the kded package.


%package dev
Summary: dev components for the kded package.
Group: Development
Requires: kded-bin
Requires: kded-data
Provides: kded-devel

%description dev
dev components for the kded package.


%package license
Summary: license components for the kded package.
Group: Default

%description license
license components for the kded package.


%package man
Summary: man components for the kded package.
Group: Default

%description man
man components for the kded package.


%prep
%setup -q -n kded-5.49.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1534113738
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1534113738
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/kded
cp COPYING.LGPL-2 %{buildroot}/usr/share/doc/kded/COPYING.LGPL-2
cp COPYING.LIB %{buildroot}/usr/share/doc/kded/COPYING.LIB
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/kded5

%files data
%defattr(-,root,root,-)
/usr/share/dbus-1/interfaces/org.kde.kded5.xml
/usr/share/dbus-1/services/org.kde.kded5.service
/usr/share/kservicetypes5/kdedmodule.desktop

%files dev
%defattr(-,root,root,-)
/usr/lib64/cmake/KDED/KDEDConfig.cmake
/usr/lib64/cmake/KDED/KDEDConfigVersion.cmake
/usr/lib64/cmake/KDED/KDEDTargets-relwithdebinfo.cmake
/usr/lib64/cmake/KDED/KDEDTargets.cmake
/usr/lib64/libkdeinit5_kded5.so

%files license
%defattr(-,root,root,-)
/usr/share/doc/kded/COPYING.LGPL-2
/usr/share/doc/kded/COPYING.LIB

%files man
%defattr(-,root,root,-)
/usr/share/man/ca/man8/kded5.8
/usr/share/man/de/man8/kded5.8
/usr/share/man/es/man8/kded5.8
/usr/share/man/it/man8/kded5.8
/usr/share/man/man8/kded5.8
/usr/share/man/nl/man8/kded5.8
/usr/share/man/pt/man8/kded5.8
/usr/share/man/pt_BR/man8/kded5.8
/usr/share/man/ru/man8/kded5.8
/usr/share/man/sv/man8/kded5.8
/usr/share/man/uk/man8/kded5.8
